/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Position = IDL.Record({ 'x' : IDL.Nat16, 'y' : IDL.Nat16 });
export const Direction = IDL.Variant({
  'east' : IDL.Null,
  'west' : IDL.Null,
  'south' : IDL.Null,
  'north' : IDL.Null,
});
export const Move = IDL.Record({
  'to' : Position,
  'direction' : Direction,
  'from' : Position,
});

export const idlService = IDL.Service({
  'createMove' : IDL.Func([Position, Direction], [Move], []),
  'getAllValidMoves' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(Position, Position))],
      ['query'],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Position = IDL.Record({ 'x' : IDL.Nat16, 'y' : IDL.Nat16 });
  const Direction = IDL.Variant({
    'east' : IDL.Null,
    'west' : IDL.Null,
    'south' : IDL.Null,
    'north' : IDL.Null,
  });
  const Move = IDL.Record({
    'to' : Position,
    'direction' : Direction,
    'from' : Position,
  });
  
  return IDL.Service({
    'createMove' : IDL.Func([Position, Direction], [Move], []),
    'getAllValidMoves' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(Position, Position))],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };